ciudad_index:
    path:     /
    defaults: { _controller: "Proyecto2Bundle:Ciudad:index" }
    methods:   [GET, POST]
    options:
            expose: true

ciudad_show:
    path:     /{id}/show
    defaults: { _controller: "Proyecto2Bundle:Ciudad:show" }
    methods:  GET



