tipo_index:
    path:     /
    defaults: { _controller: "Proyecto2Bundle:Tipo:index" }
    methods:  GET
    options:
            expose: true

tipo_show:
    path:     /{id}/show
    defaults: { _controller: "Proyecto2Bundle:Tipo:show" }
    methods:  GET



